# Generated by Django 6.1 on 2026-08-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apparatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Display order on reports and score sheets."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "apparatus",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g 2006 senior ball, candidate A", max_length=200
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="Upload a video file for the routine.",
                        upload_to="routines/",
                    ),
                ),
                (
                    "apparatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="questions.apparatus",
                    ),
                ),
            ],
            options={
                "ordering": ["apparatus__position", "label"],
            },
        ),
    ]
