# Generated by Django 6.1 on 2026-08-11 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("DA", "Apparatus Difficulty"),
                            ("DB", "Body Difficulty"),
                            ("AV", "Artistic Value"),
                            ("EX", "Execution"),
                        ],
                        help_text="e.g 'DA', 'DB', 'AV', 'EX'",
                        max_length=2,
                    ),
                ),
                (
                    "expert_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expert score for this item.",
                        max_digits=4,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        help_text="The routine this item belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="questions.routine",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("routine", "aspect"),
                        name="uq_one_item_per_aspect_per_routine",
                    )
                ],
            },
        ),
    ]
