# Generated by Django 6.1 on 2026-08-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_practicalitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="e.g. 'RG-2026-014'", max_length=50, unique=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes or context for the question.",
                    ),
                ),
            ],
            options={
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Display order of the option."
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this option is the correct answer.",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_correct", True)),
                        fields=("question",),
                        name="uq_one_correct_option_per_question",
                    ),
                    models.UniqueConstraint(
                        fields=("question", "position"),
                        name="uq_unique_option_position_per_question",
                    ),
                ],
            },
        ),
    ]
