# Generated by Django 6.1 on 2026-08-15 09:21

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_question_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                        ],
                        help_text="Type of content block.",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Display order of the content block."
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Text content for the block."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image content for the block.",
                        upload_to="blocks/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video content for the block.",
                        upload_to="blocks/",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="questions.option",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "TEXT"),
                                models.Q(("text", ""), _negated=True),
                                ("image", ""),
                                ("video", ""),
                            ),
                            models.Q(
                                ("kind", "IMAGE"),
                                models.Q(("image", ""), _negated=True),
                                ("text", ""),
                                ("video", ""),
                            ),
                            models.Q(
                                ("kind", "VIDEO"),
                                models.Q(("video", ""), _negated=True),
                                ("text", ""),
                                ("image", ""),
                            ),
                            _connector="OR",
                        ),
                        name="questions_optionblock_kind_matches_payload",
                    ),
                    models.UniqueConstraint(
                        deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                        fields=("option", "position"),
                        name="uq_unique_block_position_per_option",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                        ],
                        help_text="Type of content block.",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Display order of the content block."
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Text content for the block."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image content for the block.",
                        upload_to="blocks/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video content for the block.",
                        upload_to="blocks/",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "TEXT"),
                                models.Q(("text", ""), _negated=True),
                                ("image", ""),
                                ("video", ""),
                            ),
                            models.Q(
                                ("kind", "IMAGE"),
                                models.Q(("image", ""), _negated=True),
                                ("text", ""),
                                ("video", ""),
                            ),
                            models.Q(
                                ("kind", "VIDEO"),
                                models.Q(("video", ""), _negated=True),
                                ("text", ""),
                                ("image", ""),
                            ),
                            _connector="OR",
                        ),
                        name="questions_questionblock_kind_matches_payload",
                    ),
                    models.UniqueConstraint(
                        deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                        fields=("question", "position"),
                        name="uq_unique_block_position_per_question",
                    ),
                ],
            },
        ),
    ]
