# Generated by Django 6.1 on 2026-08-23 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_add_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routine",
            options={"ordering": ["apparatus__position", "label", "pk"]},
        ),
    ]
