"""added question_category column

Revision ID: d1fe40a5306a
Revises: 00ad040537b5
Create Date: 2019-05-28 15:27:01.901166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fe40a5306a'
down_revision = '00ad040537b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('question_category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_questions', 'question_category')
    # ### end Alembic commands ###
