"""added practical progress column

Revision ID: 00ad040537b5
Revises: 81e62d12fac1
Create Date: 2019-05-28 07:42:03.007676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ad040537b5'
down_revision = '81e62d12fac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_result', sa.Column('practical_progress', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_result', 'practical_progress')
    # ### end Alembic commands ###
