"""added exam end date

Revision ID: 74fef3710ed9
Revises: c05d2272e057
Create Date: 2019-08-08 07:48:48.974992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fef3710ed9'
down_revision = 'c05d2272e057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_result', sa.Column('exam_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_result', 'exam_end_date')
    # ### end Alembic commands ###
