"""empty message

Revision ID: c05d2272e057
Revises: d1fe40a5306a
Create Date: 2019-07-21 11:05:29.221627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05d2272e057'
down_revision = 'd1fe40a5306a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_practial_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decipline', sa.String(length=64), nullable=True),
    sa.Column('internal_question_value', sa.String(length=64), nullable=True),
    sa.Column('result_question_value', sa.String(length=64), nullable=True),
    sa.Column('control_score', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_practial_answers')
    # ### end Alembic commands ###
