# Generated by Django 6.1 on 2026-08-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="The level of the sitting judge"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(help_text="The year of the exam"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PRACTICAL", "Practical"), ("THEORY", "Theory")],
                        help_text="The kind of the exam",
                        max_length=9,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "level", "kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "year", "kind"),
                        name="uq_one_exam_per_level_year_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["PRACTICAL", "THEORY"])),
                        name="ck_exam_kind_is_valid",
                    ),
                ],
            },
        ),
    ]
