# Generated by Django 6.1 on 2026-08-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the exam component i.e 'Apparatus Difficulty'",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="The position of the exam component in the exam"
                    ),
                ),
                (
                    "marking_scheme",
                    models.CharField(
                        choices=[("CHOICE", "Choice"), ("NUMERIC", "Numeric")],
                        help_text="The marking scheme for this component",
                        max_length=7,
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DA", "Apparatus Difficulty"),
                            ("DB", "Body Difficulty"),
                            ("AV", "Artistic Value"),
                            ("EX", "Execution"),
                        ],
                        help_text="The aspect of the exam component i.e. 'DA' or '' if theory",
                        max_length=2,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "position"),
                        name="uq_one_component_position_per_exam",
                    ),
                    models.UniqueConstraint(
                        fields=("exam", "aspect"),
                        name="uq_one_component_per_aspect_per_exam",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("marking_scheme__in", ["CHOICE", "NUMERIC"])
                        ),
                        name="ck_component_marking_scheme_is_valid",
                    ),
                ],
            },
        ),
    ]
