# Generated by Django 6.1 on 2026-08-29 18:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_examcomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="examcomponent",
            name="difference_steps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(
                    decimal_places=2,
                    help_text="The difference step for this component",
                    max_digits=4,
                ),
                default=[],
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MarkingTableRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expert_minimum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The expert minimum for this marking table row",
                        max_digits=4,
                    ),
                ),
                (
                    "percentages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(
                            decimal_places=2,
                            help_text="The percentage for this marking table row",
                            max_digits=5,
                        )
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marking_rows",
                        to="exams.examcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["expert_minimum"],
            },
        ),
        migrations.CreateModel(
            name="GradeBandRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the grade band row i.e 'Excellent' or 'Good'",
                        max_length=50,
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The minimum value for this grade band including the lower bound",
                        max_digits=4,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_bands",
                        to="exams.examcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["minimum"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component", "name"),
                        name="uq_one_band_per_name_per_component",
                    )
                ],
            },
        ),
    ]
