# Generated by Django 6.1 on 2026-08-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_examcomponent_difference_steps_markingtablerow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradebandrow",
            name="minimum",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The minimum value for this grade band including the lower bound",
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="markingtablerow",
            constraint=models.UniqueConstraint(
                fields=("component", "expert_minimum"),
                name="uq_one_row_per_expert_minimum_per_component",
            ),
        ),
    ]
