# Generated by Django 6.1 on 2026-08-30 06:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_alter_gradebandrow_minimum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examcomponent",
            name="difference_steps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    default=list,
                    help_text="The difference step for this component",
                    max_digits=4,
                )
            ),
        ),
        migrations.AddConstraint(
            model_name="examcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("difference_steps__len__gt", 0), ("marking_scheme", "NUMERIC")
                    ),
                    models.Q(
                        ("difference_steps__len", 0), ("marking_scheme", "CHOICE")
                    ),
                    _connector="OR",
                ),
                name="ck_component_steps_match_marking_scheme",
            ),
        ),
    ]
