# Generated by Django 6.1 on 2026-08-31 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_alter_examcomponent_difference_steps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examcomponent",
            name="difference_steps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(
                    decimal_places=2,
                    help_text="The difference step for this component",
                    max_digits=4,
                ),
                blank=True,
                default=list,
            ),
        ),
    ]
