# Generated by Django 6.1 on 2026-08-31 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0006_alter_examcomponent_difference_steps"),
        ("questions", "0006_routine_ordering_add_pk_tiebreak"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentPracticalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="The position of the practical item within the component."
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practical_item_members",
                        to="exams.examcomponent",
                    ),
                ),
                (
                    "practical_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_memberships",
                        to="questions.practicalitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component", "position"),
                        name="uq_one_practical_item_position_per_component",
                    ),
                    models.UniqueConstraint(
                        fields=("component", "practical_item"),
                        name="uq_one_practical_item_per_component",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="The position of the question within the component."
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_members",
                        to="exams.examcomponent",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_memberships",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component", "position"),
                        name="uq_one_question_position_per_component",
                    ),
                    models.UniqueConstraint(
                        fields=("component", "question"),
                        name="uq_one_question_per_component",
                    ),
                ],
            },
        ),
    ]
