# Generated by Django 6.1 on 2026-09-05 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0008_historicalsitting_sitting"),
    ]

    operations = [
        migrations.CreateModel(
            name="SittingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=50)),
                ("component_position", models.PositiveSmallIntegerField()),
                ("marking_scheme", models.CharField(max_length=7)),
                ("position", models.PositiveSmallIntegerField()),
                ("question_snapshot", models.JSONField()),
                ("marking_key", models.JSONField()),
                ("response", models.JSONField(null=True)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "sitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="exams.sitting",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sitting", "position"),
                        name="uq_one_item_position_per_sitting",
                    )
                ],
            },
        ),
    ]
